export const cartTypes = {
    LOAD_CART:'Cart - LOAD_CART',
    ADD_TO_CART_QUANTITY:'Cart - ADD_TO_CART_QUANTITY',
    ADD_TO_CART_PRODUCT:'Cart - ADD_TO_CART_PRODUCT',
    CHANGE_CART__PRODUCT:'Cart - CHANGE_CART__PRODUCT',
    DELETE_CART:'Cart - DELETE_CART',
}