export const cartTypes = {
  SET_CART: 'CART - SET_CART',
  // LOAD_CART:'CART - LOAD_CART',
  // ADD_TO_CART_QUANTITY:'CART - ADD_TO_CART_QUANTITY',
  // ADD_TO_CART_PRODUCT:'CART - ADD_TO_CART_PRODUCT',
  // CHANGE_CART__PRODUCT:'CART - CHANGE_CART__PRODUCT',
  // DELETE_CART:'CART - DELETE_CART',
}