import style from './signInForm.module.scss'

export const signInFormFields = [
  {
    tagType: 'regular',
    label: "First name",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    id: "firstName",
    name: "firstName",
    type: "text",
    placeholder: "John",
  },
  {
    tagType: 'regular',
    label: "Last Name",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    id: "lastName",
    name: "lastName",
    type: "text",
    placeholder: "Smith",
  },
  {
    tagType: 'regular',
    label: "Login",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    id: "login",
    name: "login",
    type: "text",
    placeholder: "JohnSmith",
  },
  {
    tagType: 'regular',
    label: "Email",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    id: "email",
    name: "email",
    type: "email",
    placeholder: "example@gmail.com",
  },
  {
    tagType: 'regular',
    label: "Password",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    id: "password",
    name: "password",
    type: "text",
    placeholder: "******",
  },
  {
    tagType: 'masked',
    label: "Phone number",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    id: "telephone",
    name: "telephone",
    type: "text",
    format: "+380#########",
    mask: "#",
  }
]
