import style from './signInForm.module.scss'

export const signInFormFields = [
  {
    tagType: 'regular',
    label: "Ім'я користувача",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    name: "firstName",
    type: "text",
    placeholder: "John",
  },
  {
    tagType: 'regular',
    label: "Прізвище користувача",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    name: "lastName",
    type: "text",
    placeholder: "Smith",
  },
  {
    tagType: 'regular',
    label: "Логін",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    name: "login",
    type: "text",
    placeholder: "JohnSmith",
  },
  {
    tagType: 'regular',
    label: "Email",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    name: "email",
    type: "email",
    placeholder: "example@gmail.com",
  },
  {
    tagType: 'regular',
    label: "Пароль",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    name: "password",
    type: "text",
    placeholder: "******",
  },
  {
    tagType: 'masked',
    label: "Мобільний телефон",
    labelClass: style.form__label,
    inputClass: style.form__input,
    errorClass: style.form__error,
    name: "phone",
    type: "string",
    format: "(###) ###-##-##",
    mask: "#",
  }
]
